### ISSUE TITLE
Drupal 8 version

### ISSUE THREAD

**Issue by Muffinman** [makinacorpus/drupal-filechunk#4]
Hi,

This seems like a really useful module, are there any plans to port it Drupal 8?

**Comment by pounard** [comment]
Hello, I kinda quit Drupal development a couple of years ago, so there won't be a Drupal 8 version, at least not developed by me (I'm the original author).

For what it worth, you might want to look at the Symfony bundle at https://github.com/makinacorpus/filechunk-bundle we continue to maintain and use on various production sites, since it embeds the necessary controllers and server side logic, it might be not that hard to plug it manually into a Drupal 8 site (or create your own variant), you would have to:

 - find a way to make the controller Drupal >=8 compatible, this should be relatively easy,
 - create your own form element implementation for it (OK, that one is not an easy one, believe me, but doable).

**Comment by Muffinman** [comment]
Thanks for your feedback!

With my use case I actually needed it as a Webform Field/Element, but I thought a Drupal 8 version of this might be a good starting point.

I've been trying to integrate the Drupal 8 Plupload module (which does support chunking) into a webform Element, with limited success at the moment!

**Comment by pounard** [comment]
Juste as a note, the JS widget has its own package and can be used easily, yet it is undocumented and heavily tied to server side implémentation, that's two things we have to improve. If we manage to get some r&d time over that feature we may be do it, but I can't promise anything...
